name: CI
on:
  repository_dispatch:
    types:
      - webhook-1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          git config --global user.email "zhanhui@zju.edu.cn"
          git config --global user.name "zhanhui1999"
          rm -rf DGLD
          git clone https://zhanhui1999:${{ secrets.PERSONAL_TOKEN }}@github.com/EagleLab-ZJU/DGLD.git
          cd DGLD
          git checkout main
          rm -rf .git
          cd ..
          git add .
          git commit -m "submodule update"
          git push origin master
